package personaltrainer.model;
// Generated 14-ago-2017 23:50:33 by Hibernate Tools 5.2.3.Final

/**
 * ClienteCoach generated by hbm2java
 */
public class ClienteCoach implements java.io.Serializable {

	private ClienteCoachId id;
	private Cliente cliente;
	private Coach coach;

	public ClienteCoach() {
	}

	public ClienteCoach(ClienteCoachId id, Cliente cliente, Coach coach) {
		this.id = id;
		this.cliente = cliente;
		this.coach = coach;
	}

	public ClienteCoachId getId() {
		return this.id;
	}

	public void setId(ClienteCoachId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Coach getCoach() {
		return this.coach;
	}

	public void setCoach(Coach coach) {
		this.coach = coach;
	}

}
