package personaltrainer.model;
// Generated 14-ago-2017 23:50:33 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ejercicio generated by hbm2java
 */
public class Ejercicio implements java.io.Serializable {

	private Integer id;
	private Catalogo catalogo;
	private String nombre;
	private String descripcion;
	private String descripcionCorta;
	private String video;
	private String activo;
	private String equipamiento;
	private Set<RutinaEjercicio> rutinaEjercicios = new HashSet<RutinaEjercicio>(0);

	public Ejercicio() {
	}

	public Ejercicio(Catalogo catalogo, String nombre, String descripcionCorta, String activo) {
		this.catalogo = catalogo;
		this.nombre = nombre;
		this.descripcionCorta = descripcionCorta;
		this.activo = activo;
	}

	public Ejercicio(Catalogo catalogo, String nombre, String descripcion, String descripcionCorta, String video,
			String activo, String equipamiento, Set<RutinaEjercicio> rutinaEjercicios) {
		this.catalogo = catalogo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.descripcionCorta = descripcionCorta;
		this.video = video;
		this.activo = activo;
		this.equipamiento = equipamiento;
		this.rutinaEjercicios = rutinaEjercicios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Catalogo getCatalogo() {
		return this.catalogo;
	}

	public void setCatalogo(Catalogo catalogo) {
		this.catalogo = catalogo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDescripcionCorta() {
		return this.descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}

	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public String getEquipamiento() {
		return this.equipamiento;
	}

	public void setEquipamiento(String equipamiento) {
		this.equipamiento = equipamiento;
	}

	public Set<RutinaEjercicio> getRutinaEjercicios() {
		return this.rutinaEjercicios;
	}

	public void setRutinaEjercicios(Set<RutinaEjercicio> rutinaEjercicios) {
		this.rutinaEjercicios = rutinaEjercicios;
	}

}
