package personaltrainer.model;
// Generated 14-ago-2017 23:50:33 by Hibernate Tools 5.2.3.Final

/**
 * PlanRutina generated by hbm2java
 */
public class PlanRutina implements java.io.Serializable {

	private Integer id;
	private Plan plan;
	private Rutina rutina;

	public PlanRutina() {
	}

	public PlanRutina(Plan plan, Rutina rutina) {
		this.plan = plan;
		this.rutina = rutina;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	public Rutina getRutina() {
		return this.rutina;
	}

	public void setRutina(Rutina rutina) {
		this.rutina = rutina;
	}

}
