package personaltrainer.model;
// Generated 14-ago-2017 23:50:33 by Hibernate Tools 5.2.3.Final

/**
 * PlanCliente generated by hbm2java
 */
public class PlanCliente implements java.io.Serializable {

	private PlanClienteId id;
	private Cliente cliente;
	private Plan plan;

	public PlanCliente() {
	}

	public PlanCliente(PlanClienteId id, Cliente cliente, Plan plan) {
		this.id = id;
		this.cliente = cliente;
		this.plan = plan;
	}

	public PlanClienteId getId() {
		return this.id;
	}

	public void setId(PlanClienteId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

}
