package personaltrainer.model;
// Generated 14-ago-2017 23:50:33 by Hibernate Tools 5.2.3.Final

/**
 * RutinaEjercicio generated by hbm2java
 */
public class RutinaEjercicio implements java.io.Serializable {

	private Integer id;
	private Ejercicio ejercicio;
	private Rutina rutina;
	private int duracionRepet;

	public RutinaEjercicio() {
	}

	public RutinaEjercicio(Ejercicio ejercicio, Rutina rutina, int duracionRepet) {
		this.ejercicio = ejercicio;
		this.rutina = rutina;
		this.duracionRepet = duracionRepet;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ejercicio getEjercicio() {
		return this.ejercicio;
	}

	public void setEjercicio(Ejercicio ejercicio) {
		this.ejercicio = ejercicio;
	}

	public Rutina getRutina() {
		return this.rutina;
	}

	public void setRutina(Rutina rutina) {
		this.rutina = rutina;
	}

	public int getDuracionRepet() {
		return this.duracionRepet;
	}

	public void setDuracionRepet(int duracionRepet) {
		this.duracionRepet = duracionRepet;
	}

}
