package personaltrainer.model;
// Generated 14-ago-2017 23:50:33 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rutina generated by hbm2java
 */
public class Rutina implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set<RutinaEjercicio> rutinaEjercicios = new HashSet<RutinaEjercicio>(0);
	private Set<PlanRutina> planRutinas = new HashSet<PlanRutina>(0);

	public Rutina() {
	}

	public Rutina(String nombre, Set<RutinaEjercicio> rutinaEjercicios, Set<PlanRutina> planRutinas) {
		this.nombre = nombre;
		this.rutinaEjercicios = rutinaEjercicios;
		this.planRutinas = planRutinas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<RutinaEjercicio> getRutinaEjercicios() {
		return this.rutinaEjercicios;
	}

	public void setRutinaEjercicios(Set<RutinaEjercicio> rutinaEjercicios) {
		this.rutinaEjercicios = rutinaEjercicios;
	}

	public Set<PlanRutina> getPlanRutinas() {
		return this.planRutinas;
	}

	public void setPlanRutinas(Set<PlanRutina> planRutinas) {
		this.planRutinas = planRutinas;
	}

}
